#define CONDITIONAL                      1
#define OR                               2
#define AND                              3
#define NOT                              4
#define GREATER                          5
#define GREATER_EQUAL                    6
#define EQUALS                           7
#define SMALLER_EQUAL                    8
#define SMALLER                          9
#define MINUS                           10
#define PLUS                            11
#define MUL                             12
#define DIV                             13
#define MOD                             14
#define VOID                            15
#define VAR                             16
#define LPAREN                          17
#define RPAREN                          18
#define LBR                             19
#define RBR                             20
#define INT                             21
#define LSQBR                           22
#define RSQBR                           23
#define COMMA                           24
#define ABSTRACTION_START               25
#define PREDICATE_TOKEN                 26
#define COLON                           27
#define ABSTRACTION_END                 28
#define ABSTRACTION_TOKEN               29
#define IF                              30
#define WHILE                           31
#define ASSERT                          32
#define SKIP                            33
#define SEMI                            34
#define ELSE                            35
#define FORALL                          36
#define IN                              37
#define TRUE                            38
#define FALSE                           39
#define ASSIGN                          40
#define CONST                           41
